version: "{branch} {build}"

# Do not build feature branch on additional commits with open Pull Requests.
# See: https://help.appveyor.com/discussions/questions/18437-skip_branch_with_pr-setting-doesnt-work
skip_branch_with_pr: true

build:
  verbosity: detailed

# Ensure `config` sub-module is initialized
before_build:
  - git submodule update --init --recursive

build_script:
  - gradlew build --stacktrace

test_script:
  - gradlew check --stacktrace

after_build:
  # upload test results via rest-api
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      Get-ChildItem . -Name -Recurse 'TEST-*.xml'  |
      Foreach-Object {
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
      }

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true
